[project]
name = "poseidon"
version = "0.1.0"
description = "Poseidon implementation for Binary Merkle Tree in Leo"
license = "MIT"

[remote]
author = "[AUTHOR]" # Add your Aleo Package Manager username or team name.
